const QUESTIONS_RAW = [
  // ── LV1: 基本スキルコード（12問）──────────────────────────────
  {skill:"S",level:1,
   players:{A:7},
   scene:{
     desc:"{A}番がサーブを打った。",
     ball:[{fx:245,fy:222,tx:150,ty:66}],
     actors:[{n:"A",side:"home",x:245,y:220}],
     hlHome:[1],hlAway:[],
   },
   answer:"{A}S",variants:["{A}S"],
   explanation:"基本形：背番号＋S。評価なしはラリーが続いた状態。"},

  {skill:"S",level:1,
   players:{A:3},
   scene:{
     desc:"{A}番のサーブがエースになった！",
     ball:[{fx:55,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:55,y:220}],
     hlHome:[5],hlAway:[6],result:"ace",
   },
   answer:"{A}S#",variants:["{A}S#"],
   explanation:"決定は「#」。サーブエース = {A}S#。"},

  {skill:"S",level:1,
   players:{A:11},
   scene:{
     desc:"{A}番のサーブがネットに引っかかった。",
     ball:[{fx:150,fy:218,tx:150,ty:115,net:true}],
     actors:[{n:"A",side:"home",x:150,y:218}],
     hlHome:[6],hlAway:[],result:"miss",
   },
   answer:"{A}S=",variants:["{A}S="],
   explanation:"サーブのネット・アウトはどちらも「=」ミス。{A}S=で記録。"},

  {skill:"A",level:1,
   players:{A:5},
   scene:{
     desc:"{A}番がスパイクを打って得点！",
     ball:[{fx:70,fy:128,tx:110,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"ace",
   },
   answer:"{A}A#",variants:["{A}A#"],
   explanation:"A = アタック。スパイク決定は「#」。{A}A#。"},

  {skill:"A",level:1,
   players:{A:4},
   scene:{
     desc:"{A}番がスパイクを打ったがアウトになった。",
     ball:[{fx:70,fy:128,tx:30,ty:215,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"miss",
   },
   answer:"{A}A=",variants:["{A}A="],
   explanation:"スパイクのアウト・ネットはどちらも「=」ミス。{A}A=。"},

  {skill:"B",level:1,
   players:{A:2},
   scene:{
     desc:"自チーム{A}番が相手スパイクをブロックして得点！",
     ball:[{fx:230,fy:98,tx:230,ty:115},{fx:230,fy:115,tx:210,ty:185}],
     actors:[{n:"A",side:"home",x:230,y:128,jump:true},{n:6,side:"away",x:230,y:98,jump:true}],
     hlHome:[2],hlAway:[],result:"ace",
   },
   answer:"{A}B#",variants:["{A}B#"],
   explanation:"B = Block。ブロック決定は「#」。{A}B#。"},

  {skill:"B",level:1,
   players:{A:8},
   scene:{
     desc:"{A}番がブロックに跳んだが、ボールが自コートに落ちた。",
     ball:[{fx:150,fy:96,tx:150,ty:185}],
     actors:[{n:"A",side:"home",x:150,y:128,jump:true},{n:11,side:"away",x:150,y:96,jump:true}],
     hlHome:[],hlAway:[],result:"bad",
   },
   answer:"{A}B=",variants:["{A}B="],
   explanation:"ブロックできず失点 = B=。"},

  {skill:"E",level:1,
   players:{A:10},
   scene:{
     desc:"セッター{A}番がトスを上げた。",
     ball:[{fx:150,fy:162,tx:150,ty:130},{fx:150,fy:130,tx:70,ty:130}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],
   },
   answer:"{A}E",variants:["{A}E"],
   explanation:"E = sEt（トス）。評価なしは通常のトス。"},

  {skill:"D",level:1,
   players:{A:8},
   scene:{
     desc:"相手スパイクを自チーム{A}番がディグした。",
     ball:[{fx:230,fy:98,tx:150,ty:162},{fx:150,fy:162,tx:150,ty:145}],
     actors:[{n:"A",side:"home",x:150,y:160},{n:4,side:"away",x:230,y:98,jump:true}],
     hlHome:[8],hlAway:[],
   },
   answer:"{A}D",variants:["{A}D","{A}D!"],
   explanation:"D = Dig（スパイクレシーブ）。評価なし（または!）は普通のディグ。"},

  {skill:"D",level:1,
   players:{A:6},
   scene:{
     desc:"相手のスパイクを{A}番がディグできなかった。",
     ball:[{fx:230,fy:98,tx:180,ty:175}],
     actors:[{n:"A",side:"home",x:180,y:175},{n:9,side:"away",x:230,y:96,jump:true}],
     hlHome:[],hlAway:[],result:"bad",
   },
   answer:"{A}D=",variants:["{A}D="],
   explanation:"ディグミス（拾えず失点）= D=。"},

  {skill:"R",level:1,
   players:{A:3},
   scene:{
     desc:"{A}番がサーブレシーブした。",
     ball:[{fx:150,fy:15,tx:70,ty:195}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],
   },
   answer:"{A}R",variants:["{A}R","{A}R!"],
   explanation:"R = Reception（サーブレシーブ）。評価なし（または!）は普通のレシーブ。"},

  {skill:"R",level:1,
   players:{A:5},
   scene:{
     desc:"{A}番がサーブレシーブをミスした。",
     ball:[{fx:150,fy:15,tx:70,ty:195}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"miss",
   },
   answer:"{A}R=",variants:["{A}R="],
   explanation:"レセプションミス = {A}R=。相手サーブエースと同義。"},

  // ── LV2: 評価 + 味方/相手ランダム（15問, sideRandom）──────────
  {skill:"R",level:2,sideRandom:true,
   players:{A:3},
   scene:{
     desc:"{PRE}{A}番のレセプションが完璧だった（評価#）。",
     ball:[{fx:150,fy:15,tx:70,ty:193}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}R#",variants:["{APRE}{A}R#"],
   explanation:"{APRE}{A}R# = {PRE}{A}番のパーフェクトレセプション。セッターが自由にトスを上げられる。"},

  {skill:"R",level:2,sideRandom:true,
   players:{A:4},
   scene:{
     desc:"{PRE}{A}番のレセプション評価は+（優れた）。",
     ball:[{fx:150,fy:15,tx:70,ty:193}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}R+",variants:["{APRE}{A}R+"],
   explanation:"{APRE}{A}R+ = {PRE}{A}番の優れたレセプション。"},

  {skill:"R",level:2,sideRandom:true,
   players:{A:7},
   scene:{
     desc:"{PRE}{A}番のレセプション評価は！（普通）。",
     ball:[{fx:150,fy:15,tx:150,ty:193}],
     actors:[{n:"A",side:"home",x:150,y:193}],
     hlHome:[6],hlAway:[],
   },
   answer:"{APRE}{A}R!",variants:["{APRE}{A}R!","{APRE}{A}R"],
   explanation:"{APRE}{A}R! = {PRE}{A}番の普通のレセプション。評価なしと同義。"},

  {skill:"R",level:2,sideRandom:true,
   players:{A:9},
   scene:{
     desc:"{PRE}{A}番のレセプション評価はー（やや悪い）。",
     ball:[{fx:150,fy:15,tx:230,ty:193}],
     actors:[{n:"A",side:"home",x:230,y:193}],
     hlHome:[1],hlAway:[],result:"bad",
   },
   answer:"{APRE}{A}R-",variants:["{APRE}{A}R-"],
   explanation:"{APRE}{A}R- = {PRE}{A}番のやや悪いレセプション。セッターの選択肢が狭まる。"},

  {skill:"A",level:2,sideRandom:true,
   players:{A:5},
   scene:{
     desc:"{PRE}{A}番のスパイクがブロックされた。",
     ball:[{fx:70,fy:128,tx:150,ty:115,spike:true},{fx:150,fy:115,tx:70,ty:185}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"bad",
   },
   answer:"{APRE}{A}A/",variants:["{APRE}{A}A/"],
   explanation:"{APRE}{A}A/ = {PRE}{A}番のスパイクがブロックされた。「/」はブロックされた評価。"},

  {skill:"D",level:2,sideRandom:true,
   players:{A:8},
   scene:{
     desc:"{PRE}{A}番のディグ評価は+（優れた）。",
     ball:[{fx:230,fy:96,tx:150,ty:162}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}D+",variants:["{APRE}{A}D+"],
   explanation:"{APRE}{A}D+ = {PRE}{A}番の優れたディグ。セッターが上げやすい好レシーブ。"},

  {skill:"D",level:2,sideRandom:true,
   players:{A:11},
   scene:{
     desc:"{PRE}{A}番のディグ評価は！（普通）。",
     ball:[{fx:230,fy:96,tx:150,ty:162}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],
   },
   answer:"{APRE}{A}D!",variants:["{APRE}{A}D!","{APRE}{A}D"],
   explanation:"{APRE}{A}D! = {PRE}{A}番の普通のディグ。評価なしと同義。"},

  {skill:"D",level:2,sideRandom:true,
   players:{A:6},
   scene:{
     desc:"{PRE}{A}番のディグ評価はー（やや悪い）。",
     ball:[{fx:230,fy:96,tx:230,ty:193}],
     actors:[{n:"A",side:"home",x:230,y:193}],
     hlHome:[1],hlAway:[],result:"bad",
   },
   answer:"{APRE}{A}D-",variants:["{APRE}{A}D-"],
   explanation:"{APRE}{A}D- = {PRE}{A}番のやや悪いディグ。セッターの選択肢が狭まる。"},

  {skill:"E",level:2,sideRandom:true,
   players:{A:1},
   scene:{
     desc:"{PRE}{A}番（セッター）のトス評価は+（優れた）。",
     ball:[{fx:150,fy:162,tx:150,ty:130},{fx:150,fy:130,tx:70,ty:130}],
     actors:[{n:"A",side:"home",x:150,y:160}],
     hlHome:[8],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}E+",variants:["{APRE}{A}E+"],
   explanation:"{APRE}{A}E+ = {PRE}{A}番の優れたセット。アタッカーが打ちやすいトス。"},

  {skill:"E",level:2,sideRandom:true,
   players:{A:2},
   scene:{
     desc:"{PRE}{A}番（セッター）のトス評価はー（やや悪い）。",
     ball:[{fx:150,fy:162,tx:150,ty:130},{fx:150,fy:130,tx:230,ty:130}],
     actors:[{n:"A",side:"home",x:150,y:160}],
     hlHome:[8],hlAway:[],result:"bad",
   },
   answer:"{APRE}{A}E-",variants:["{APRE}{A}E-"],
   explanation:"{APRE}{A}E- = {PRE}{A}番のやや悪いセット。アタッカーが打ちにくいトス。"},

  {skill:"S",level:2,sideRandom:true,
   players:{A:7},
   scene:{
     desc:"{PRE}{A}番のサーブがエースになった！",
     ball:[{fx:150,fy:218,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:150,y:218}],
     hlHome:[6],hlAway:[8],result:"ace",
   },
   answer:"{APRE}{A}S#",variants:["{APRE}{A}S#"],
   explanation:"{APRE}{A}S# = {PRE}{A}番のサーブエース。"},

  {skill:"S",level:2,sideRandom:true,
   players:{A:9},
   scene:{
     desc:"{PRE}{A}番のサーブがアウトになった。",
     ball:[{fx:150,fy:218,tx:150,ty:8}],
     actors:[{n:"A",side:"home",x:150,y:218}],
     hlHome:[6],hlAway:[],result:"miss",
   },
   answer:"{APRE}{A}S=",variants:["{APRE}{A}S="],
   explanation:"{APRE}{A}S= = {PRE}{A}番のサーブミス（ネット/アウト）。"},

  {skill:"A",level:2,sideRandom:true,
   players:{A:5},
   scene:{
     desc:"{PRE}{A}番がスパイクを打って得点！",
     ball:[{fx:70,fy:128,tx:110,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"ace",
   },
   answer:"{APRE}{A}A#",variants:["{APRE}{A}A#"],
   explanation:"{APRE}{A}A# = {PRE}{A}番のスパイク決定。"},

  {skill:"A",level:2,sideRandom:true,
   players:{A:11},
   scene:{
     desc:"{PRE}{A}番のスパイクがアウトになった。",
     ball:[{fx:70,fy:128,tx:30,ty:215,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"miss",
   },
   answer:"{APRE}{A}A=",variants:["{APRE}{A}A="],
   explanation:"{APRE}{A}A= = {PRE}{A}番のスパイクミス（アウト/ネット）。"},

  {skill:"B",level:2,sideRandom:true,
   players:{A:2},
   scene:{
     desc:"{PRE}{A}番がブロックして得点！",
     ball:[{fx:150,fy:96,tx:150,ty:185}],
     actors:[{n:"A",side:"home",x:150,y:128,jump:true}],
     hlHome:[3],hlAway:[],result:"ace",
   },
   answer:"{APRE}{A}B#",variants:["{APRE}{A}B#"],
   explanation:"{APRE}{A}B# = {PRE}{A}番のブロック決定。"},

  // ── LV3: コンパウンドコード（15問）────────────────────────────
  {skill:"S",level:3,
   compound:true,
   players:{A:7,B:3},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がレシーブした（評価！）。コンパウンドコードで入力せよ。",
     ball:[{fx:55,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:150,ty:162}],
     actors:[{n:"A",side:"away",x:55,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[1],
   },
   answer:"a{A}S.{B}!",variants:["a{A}S.{B}!","a{A}S.{B}"],
   explanation:"a{A}S.{B}! → CODE1: a{A}S（相手{A}番サーブ）/ CODE2: {B}R!（自チーム{B}番の普通レシーブ）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:8,B:3},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番が優れたレセプション（+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:150,ty:162}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"good",
   },
   answer:"a{A}S.{B}+",variants:["a{A}S.{B}+"],
   explanation:"a{A}S.{B}+ → CODE1: a{A}S / CODE2: {B}R+（自チーム{B}番の優れたレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:6,B:4},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がレシーブミスした。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:195}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"miss",
   },
   answer:"a{A}S.{B}=",variants:["a{A}S.{B}="],
   explanation:"a{A}S.{B}= → CODE1: a{A}S / CODE2: {B}R=（自チーム{B}番のレセプションミス）。相手サーブエースと同義。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:7,B:3},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番がレセプションミスした。コンパウンドコードで入力せよ。",
     ball:[{fx:55,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:55,y:220},{n:"B",side:"away",x:150,y:34}],
     hlHome:[5],hlAway:[6],result:"ace",
   },
   answer:"{A}S.{B}=",variants:["{A}S.{B}="],
   explanation:"{A}S.{B}= → CODE1: {A}S / CODE2: a{B}R=（相手{B}番のレセプションミス）。サーブエースと同義。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:5,B:8},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番がブロック決定した。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:128,tx:150,ty:66,spike:true},{fx:150,fy:66,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:"B",side:"away",x:150,y:66,jump:true}],
     hlHome:[4],hlAway:[8],result:"ace",
   },
   answer:"{A}A.{B}#",variants:["{A}A.{B}#"],
   explanation:"{A}A.{B}# → CODE1: {A}A/（ブロックされた）/ CODE2: a{B}B#（ブロック決定）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:2,B:9},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番がディグで返した。コンパウンドコードで入力せよ。",
     ball:[{fx:230,fy:128,tx:150,ty:66,spike:true},{fx:150,fy:66,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:230,y:126,jump:true},{n:"B",side:"away",x:70,y:66}],
     hlHome:[2],hlAway:[8],
   },
   answer:"{A}A.{B}D",variants:["{A}A.{B}D","{A}A.{B}D!"],
   explanation:"{A}A.{B}D → CODE1: {A}A / CODE2: a{B}D（相手{B}番のディグ）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:7,B:3},
   scene:{
     desc:"{A}番がAクイック（PA）をゾーン1方向に打ったが、相手{B}番にブロックされた。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:130,tx:70,ty:98,spike:true},{fx:70,fy:98,tx:70,ty:130}],
     actors:[{n:"A",side:"home",x:150,y:130,jump:true},{n:"B",side:"away",x:70,y:96,jump:true}],
     hlHome:[3],hlAway:[1],result:"ace",
   },
   answer:"{A}PA1.{B}#",variants:["{A}PA1.{B}#"],
   explanation:"{A}PA1.{B}# → CODE1: {A}PA1/（Aクイックがブロックされた）/ CODE2: a{B}B#（相手{B}番ブロック決定）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:4,B:9},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番がパーフェクトレセプション（#）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:55,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:55,y:220},{n:"B",side:"away",x:150,y:34}],
     hlHome:[5],hlAway:[8],result:"good",
   },
   answer:"{A}S.{B}#",variants:["{A}S.{B}#"],
   explanation:"{A}S.{B}# → CODE1: {A}S / CODE2: a{B}R#（相手{B}番のパーフェクトレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:11,B:7},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番が優れたレセプション（+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220},{n:"B",side:"away",x:150,y:34}],
     hlHome:[1],hlAway:[8],result:"good",
   },
   answer:"{A}S.{B}+",variants:["{A}S.{B}+"],
   explanation:"{A}S.{B}+ → CODE1: {A}S / CODE2: a{B}R+（相手{B}番の優れたレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:6,B:2},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番のレセプションがやや悪かった（評価ー）。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:222,tx:230,ty:34}],
     actors:[{n:"A",side:"home",x:150,y:220},{n:"B",side:"away",x:230,y:34}],
     hlHome:[6],hlAway:[5],result:"good",
   },
   answer:"{A}S.{B}-",variants:["{A}S.{B}-"],
   explanation:"{A}S.{B}- → CODE1: {A}S / CODE2: a{B}R-（相手{B}番のやや悪いレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:9,B:5},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がパーフェクトレセプション（#）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:195}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"good",
   },
   answer:"a{A}S.{B}#",variants:["a{A}S.{B}#"],
   explanation:"a{A}S.{B}# → CODE1: a{A}S（相手{A}番サーブ）/ CODE2: {B}R#（自チーム{B}番のパーフェクトレセプション）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:9,B:2},
   scene:{
     desc:"相手{A}番がスパイクを打ち、自チーム{B}番がブロック決定した。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:66,tx:70,ty:115},{fx:70,fy:115,tx:90,ty:185}],
     actors:[{n:"A",side:"away",x:70,y:64,jump:true},{n:"B",side:"home",x:70,y:128,jump:true}],
     hlHome:[4],hlAway:[9],result:"ace",
   },
   answer:"a{A}A.{B}#",variants:["a{A}A.{B}#"],
   explanation:"a{A}A.{B}# → CODE1: a{A}A/（相手{A}番のスパイクがブロックされた）/ CODE2: {B}B#（自チーム{B}番のブロック決定）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:11,B:8},
   scene:{
     desc:"相手{A}番がスパイクを打ち、自チーム{B}番がディグで返した。コンパウンドコードで入力せよ。",
     ball:[{fx:230,fy:66,tx:150,ty:162}],
     actors:[{n:"A",side:"away",x:230,y:64,jump:true},{n:"B",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],result:"good",
   },
   answer:"a{A}A.{B}D",variants:["a{A}A.{B}D","a{A}A.{B}D!"],
   explanation:"a{A}A.{B}D → CODE1: a{A}A / CODE2: {B}D（自チーム{B}番のディグ）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:3,B:6},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番が優れたディグで返した。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:128,tx:150,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:"B",side:"away",x:150,y:66}],
     hlHome:[4],hlAway:[8],result:"good",
   },
   answer:"{A}A.{B}D+",variants:["{A}A.{B}D+"],
   explanation:"{A}A.{B}D+ → CODE1: {A}A / CODE2: a{B}D+（相手{B}番の優れたディグ）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:8,B:4},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番がブロックミスして得点。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:128,tx:150,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:"B",side:"away",x:150,y:66,jump:true}],
     hlHome:[4],hlAway:[8],result:"ace",
   },
   answer:"{A}A.{B}=",variants:["{A}A.{B}="],
   explanation:"{A}A.{B}= → CODE1: {A}A#（スパイク決定）/ CODE2: a{B}B=（相手{B}番のブロックミス）。"},

  // ── LV4: ゾーン・サーブ種別詳細（12問）─────────────────────
  {skill:"S",level:4,
   players:{A:7},
   scene:{
     desc:"{A}番がゾーン1（右後）からジャンプフローターサーブを打った。",
     ball:[{fx:245,fy:222,tx:70,ty:98,curve:true}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true}],
     hlHome:[1],hlAway:[2],
   },
   answer:"{A}SM1",variants:["{A}SM1"],
   explanation:"SM = ジャンプフローター。ゾーン1（右後）から = {A}SM1。"},

  {skill:"S",level:4,
   players:{A:11},
   scene:{
     desc:"{A}番がゾーン6（中後）からジャンピングサーブを打ったがネットに当たった。",
     ball:[{fx:150,fy:222,tx:150,ty:112,net:true}],
     actors:[{n:"A",side:"home",x:150,y:220,jump:true}],
     hlHome:[6],hlAway:[],result:"miss",
   },
   answer:"{A}SQ6=",variants:["{A}SQ6="],
   explanation:"SQ = ジャンピングサーブ（トップスピン）。ゾーン6からネット = {A}SQ6=。"},

  {skill:"S",level:4,
   players:{A:1},
   scene:{
     desc:"{A}番がゾーン1（右後）からサーブを打ちエースになった！",
     ball:[{fx:245,fy:222,tx:230,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220}],
     hlHome:[1],hlAway:[5],result:"ace",
   },
   answer:"{A}S1#",variants:["{A}S1#","{A}S#"],
   explanation:"ゾーン番号はスキルの直後。{A}S1# = ゾーン1からサーブエース。"},

  {skill:"S",level:4,
   players:{A:9},
   scene:{
     desc:"{A}番がゾーン6（中後）からジャンプフローターをゾーン8（中央）に打った。",
     ball:[{fx:150,fy:222,tx:150,ty:66,curve:true}],
     actors:[{n:"A",side:"home",x:150,y:220,jump:true}],
     hlHome:[6],hlAway:[8],
   },
   answer:"{A}SM6",variants:["{A}SM6"],
   explanation:"SM = ジャンプフローター。ゾーン6（中後）から = {A}SM6。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:3,B:6},
   scene:{
     desc:"{A}番がジャンプフローターサーブを打ち、相手{B}番が優れたレセプションで返した。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:150,ty:66},{fx:150,fy:66,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true},{n:"B",side:"away",x:150,y:64}],
     hlHome:[1],hlAway:[8],result:"good",
   },
   answer:"{A}SM.{B}+",variants:["{A}SM.{B}+"],
   explanation:"{A}SM.{B}+ → CODE1: {A}SM（J.フローター）/ CODE2: a{B}R+（相手{B}番の優れたレセプション）。"},

  {skill:"A",level:4,
   players:{A:5},
   scene:{
     desc:"{A}番がレフト平行（PV）をゾーン7に打って決まった！",
     ball:[{fx:70,fy:128,tx:230,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[7],result:"ace",
   },
   answer:"{A}PV7#",variants:["{A}PV7#"],
   explanation:"PV = レフト平行。ゾーン7 = AWAY右エリア。{A}PV7#。"},

  {skill:"S",level:4,
   players:{A:6},
   scene:{
     desc:"{A}番がゾーン1（右後）からジャンピングサーブを打ちエースになった！",
     ball:[{fx:245,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true}],
     hlHome:[1],hlAway:[8],result:"ace",
   },
   answer:"{A}SQ1#",variants:["{A}SQ1#"],
   explanation:"SQ = ジャンピングサーブ。ゾーン1からエース = {A}SQ1#。"},

  {skill:"S",level:4,
   players:{A:14},
   scene:{
     desc:"{A}番がゾーン5（左後）からジャンプフローターサーブを打った。",
     ball:[{fx:55,fy:222,tx:150,ty:66,curve:true}],
     actors:[{n:"A",side:"home",x:55,y:220,jump:true}],
     hlHome:[5],hlAway:[8],
   },
   answer:"{A}SM5",variants:["{A}SM5"],
   explanation:"SM = ジャンプフローター。ゾーン5（左後）から = {A}SM5。"},

  {skill:"A",level:4,
   players:{A:3},
   scene:{
     desc:"{A}番がライト平行（PZ）をゾーン7に打って決まった！",
     ball:[{fx:230,fy:128,tx:70,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:230,y:126,jump:true}],
     hlHome:[2],hlAway:[7],result:"ace",
   },
   answer:"{A}PZ7#",variants:["{A}PZ7#"],
   explanation:"PZ = ライト平行（ゾーン2から打つ）。ゾーン7 = AWAY右エリア。{A}PZ7#。"},

  {skill:"A",level:4,
   players:{A:8},
   scene:{
     desc:"{A}番がレフト平行（PV）をゾーン4に打って決まった！",
     ball:[{fx:70,fy:128,tx:70,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[4],result:"ace",
   },
   answer:"{A}PV4#",variants:["{A}PV4#"],
   explanation:"PV = レフト平行。ゾーン4 = AWAYの左前。{A}PV4#。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:2,B:7},
   scene:{
     desc:"{A}番がゾーン1からジャンピングサーブを打ち、相手{B}番がレセプションミスした。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true},{n:"B",side:"away",x:150,y:34}],
     hlHome:[1],hlAway:[8],result:"ace",
   },
   answer:"{A}SQ1.{B}=",variants:["{A}SQ1.{B}="],
   explanation:"{A}SQ1.{B}= → CODE1: {A}SQ1（ゾーン1からジャンピングサーブ）/ CODE2: a{B}R=（相手{B}番のレセプションミス）。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:5,B:3},
   scene:{
     desc:"{A}番がゾーン6からジャンプフローターを打ち、相手{B}番が優れたレセプション（+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:222,tx:150,ty:66,curve:true},{fx:150,fy:66,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:150,y:220,jump:true},{n:"B",side:"away",x:150,y:64}],
     hlHome:[6],hlAway:[8],result:"good",
   },
   answer:"{A}SM6.{B}+",variants:["{A}SM6.{B}+"],
   explanation:"{A}SM6.{B}+ → CODE1: {A}SM6（ゾーン6からジャンプフローター）/ CODE2: a{B}R+（相手{B}番の優れたレセプション）。"},

  // ── LV5: マルチコード（8問）────────────────────────────────
  {skill:"S",level:5,
   multiCode:true,
   players:{A:1,B:3,C:4,D:6},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番がレセプション（評価#）。続いて相手{C}番がレフト平行を打ち、味方{D}番がブロックミス。2コードをスペースで区切って入力せよ。",
     ball:[{fx:240,fy:220,tx:150,ty:70},{fx:150,fy:70,tx:240,ty:180}],
     actors:[{n:"A",side:"home",x:240,y:218},{n:"B",side:"away",x:150,y:68},{n:"C",side:"away",x:180,y:80,jump:true},{n:"D",side:"home",x:200,y:190}],
     hlHome:[3],hlAway:[6,8],result:"bad",
   },
   answer:"a{B}R# a{C}PV.{D}=",variants:["a{B}R# a{C}PV.{D}="],
   explanation:"CODE1: a{B}R#（相手{B}番のパーフェクトレセプション）/ CODE2: a{C}PV.{D}=（相手{C}番のレフト平行→味方{D}番がブロックミス）。"},

  {skill:"A",level:5,
   multiCode:true,
   players:{A:5,B:2,C:7,D:9},
   scene:{
     desc:"{A}番がジャンプサーブを打ち、相手{B}番がレセプション（評価-）。続いて相手{C}番がライト平行を打ち、味方{D}番がブロックアウト。2コードをスペースで区切って入力せよ。",
     ball:[{fx:245,fy:215,tx:150,ty:75},{fx:150,fy:75,tx:250,ty:190}],
     actors:[{n:"A",side:"home",x:245,y:212,jump:true},{n:"B",side:"away",x:150,y:73},{n:"C",side:"away",x:170,y:85,jump:true},{n:"D",side:"home",x:220,y:185}],
     hlHome:[1,4],hlAway:[5,7],result:"bad",
   },
   answer:"a{B}R- a{C}PZ.{D}/",variants:["a{B}R- a{C}PZ.{D}/"],
   explanation:"CODE1: a{B}R-（相手{B}番のやや悪いレセプション）/ CODE2: a{C}PZ.{D}/（相手{C}番のライト平行→味方{D}番がブロックアウト）。"},

  {skill:"B",level:5,
   multiCode:true,
   players:{A:2,B:8,C:6,D:4},
   scene:{
     desc:"{A}番がジャンプフローターサーブを打ち、相手{B}番がレセプション（評価!）。続いて相手{C}番がAクイックを打ち、味方{D}番がブロック決定。2コードをスペースで区切って入力せよ。",
     ball:[{fx:242,fy:218,tx:155,ty:72},{fx:155,fy:72,tx:200,ty:185}],
     actors:[{n:"A",side:"home",x:242,y:215,jump:true},{n:"B",side:"away",x:155,y:70},{n:"C",side:"away",x:175,y:82,jump:true},{n:"D",side:"home",x:205,y:183}],
     hlHome:[2,5],hlAway:[6,9],result:"good",
   },
   answer:"a{B}R! a{C}PA.{D}#",variants:["a{B}R! a{C}PA.{D}#"],
   explanation:"CODE1: a{B}R!（相手{B}番の普通レセプション）/ CODE2: a{C}PA.{D}#（相手{C}番のAクイック→味方{D}番がブロック決定）。"},

  {skill:"R",level:5,
   multiCode:true,
   players:{A:2,B:5,C:8},
   scene:{
     desc:"{A}番がパーフェクトレセプション（#）。続いて{B}番がレフト平行を打ち、相手{C}番がブロック決定。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:193},{fx:70,fy:128,tx:230,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:193},{n:"B",side:"home",x:70,y:126,jump:true},{n:"C",side:"away",x:150,y:66,jump:true}],
     hlHome:[5,4],hlAway:[7],result:"bad",
   },
   answer:"{A}R# {B}PV.{C}#",variants:["{A}R# {B}PV.{C}#"],
   explanation:"CODE1: {A}R#（{A}番のパーフェクトレセプション）/ CODE2: {B}PV.{C}#（{B}番のレフト平行→相手{C}番ブロック決定）。"},

  {skill:"R",level:5,
   multiCode:true,
   players:{A:4,B:7,C:3},
   scene:{
     desc:"{A}番のレセプション評価は+。続いて{B}番がAクイックを打ち、相手{C}番が優れたディグで返した。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:193},{fx:150,fy:128,tx:150,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:193},{n:"B",side:"home",x:150,y:126,jump:true},{n:"C",side:"away",x:70,y:66}],
     hlHome:[5,3],hlAway:[],result:"good",
   },
   answer:"{A}R+ {B}PA.{C}D+",variants:["{A}R+ {B}PA.{C}D+"],
   explanation:"CODE1: {A}R+（{A}番の優れたレセプション）/ CODE2: {B}PA.{C}D+（{B}番のAクイック→相手{C}番の優れたディグ）。"},

  {skill:"A",level:5,
   multiCode:true,
   players:{A:6,B:9,C:2},
   scene:{
     desc:"相手{A}番のレセプションがパーフェクト（#）。続いて相手{B}番がライト平行を打ち、味方{C}番がブロックミス。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:15,tx:150,ty:65},{fx:230,fy:66,tx:150,ty:115,spike:true}],
     actors:[{n:"A",side:"away",x:150,y:34},{n:"B",side:"away",x:230,y:64,jump:true},{n:"C",side:"home",x:150,y:128,jump:true}],
     hlHome:[],hlAway:[8,2],result:"bad",
   },
   answer:"a{A}R# a{B}PZ.{C}=",variants:["a{A}R# a{B}PZ.{C}="],
   explanation:"CODE1: a{A}R#（相手{A}番のパーフェクトレセプション）/ CODE2: a{B}PZ.{C}=（相手{B}番のライト平行→味方{C}番がブロックミス）。"},

  {skill:"D",level:5,
   multiCode:true,
   players:{A:3,B:8,C:5},
   scene:{
     desc:"{A}番のレセプション評価はー。続いて{B}番がレフト平行を打ち、相手{C}番がディグで返した。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:15,tx:230,ty:193},{fx:70,fy:128,tx:230,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:230,y:193},{n:"B",side:"home",x:70,y:126,jump:true},{n:"C",side:"away",x:230,y:66}],
     hlHome:[1,4],hlAway:[],result:"good",
   },
   answer:"{A}R- {B}PV.{C}D",variants:["{A}R- {B}PV.{C}D"],
   explanation:"CODE1: {A}R-（{A}番のやや悪いレセプション）/ CODE2: {B}PV.{C}D（{B}番のレフト平行→相手{C}番がディグ）。"},

  {skill:"B",level:5,
   multiCode:true,
   players:{A:7,B:2,C:6},
   scene:{
     desc:"相手{A}番のレセプション評価は+。続いて相手{B}番がゾーン1方向にAクイックを打ち、味方{C}番がブロック決定。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:15,tx:150,ty:65},{fx:150,fy:66,tx:70,ty:115,spike:true}],
     actors:[{n:"A",side:"away",x:150,y:34},{n:"B",side:"away",x:150,y:66,jump:true},{n:"C",side:"home",x:70,y:128,jump:true}],
     hlHome:[4],hlAway:[8,3],result:"ace",
   },
   answer:"a{A}R+ a{B}PA1.{C}#",variants:["a{A}R+ a{B}PA1.{C}#"],
   explanation:"CODE1: a{A}R+（相手{A}番の優れたレセプション）/ CODE2: a{B}PA1.{C}#（相手{B}番のAクイック→味方{C}番がブロック決定）。"},
];

export default QUESTIONS_RAW;
