const QUESTIONS_RAW = [
  // ── LV1: 基本スキルコード（14問）──────────────────────────────
  {skill:"S",level:1,
   players:{A:7},
   scene:{
     desc:"{A}番がサーブを打った。",
     ball:[{fx:245,fy:222,tx:150,ty:66}],
     actors:[{n:"A",side:"home",x:245,y:220}],
     hlHome:[1],hlAway:[],
   },
   answer:"{A}S",variants:["{A}S"],
   explanation:"基本形：背番号＋S。評価なしはラリーが続いた状態。"},

  {skill:"S",level:1,
   players:{A:3},
   scene:{
     desc:"{A}番のサーブがエースになった！",
     ball:[{fx:55,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:55,y:220}],
     hlHome:[5],hlAway:[6],result:"ace",
   },
   answer:"{A}S#",variants:["{A}S#"],
   explanation:"決定は「#」。サーブエース = {A}S#。"},

  {skill:"S",level:1,
   players:{A:11},
   scene:{
     desc:"{A}番のサーブがネットにかかってミスになった。",
     ball:[{fx:150,fy:218,tx:150,ty:115,net:true}],
     actors:[{n:"A",side:"home",x:150,y:218}],
     hlHome:[6],hlAway:[],result:"miss",
   },
   answer:"{A}S=",variants:["{A}S="],
   explanation:"サーブのネット・アウトはどちらも「=」ミス。{A}S=で記録。"},

  {skill:"A",level:1,
   players:{A:5},
   scene:{
     desc:"{A}番がスパイクを打って得点！",
     ball:[{fx:70,fy:128,tx:110,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"ace",
   },
   answer:"{A}A#",variants:["{A}A#"],
   explanation:"A = アタック。スパイク決定は「#」。{A}A#。"},

  {skill:"A",level:1,
   players:{A:4},
   scene:{
     desc:"{A}番がスパイクを打ったがアウトになった。",
     ball:[{fx:70,fy:128,tx:30,ty:215,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"miss",
   },
   answer:"{A}A=",variants:["{A}A="],
   explanation:"スパイクのアウト・ネットはどちらも「=」ミス。{A}A=。"},

  {skill:"B",level:1,
   players:{A:2},
   scene:{
     desc:"自チーム{A}番が相手スパイクをブロックして得点！",
     ball:[{fx:230,fy:98,tx:230,ty:115},{fx:230,fy:115,tx:210,ty:185}],
     actors:[{n:"A",side:"home",x:230,y:128,jump:true},{n:6,side:"away",x:230,y:98,jump:true}],
     hlHome:[2],hlAway:[],result:"ace",
   },
   answer:"{A}B#",variants:["{A}B#"],
   explanation:"B = Block。ブロック決定は「#」。{A}B#。"},

  {skill:"B",level:1,
   players:{A:8},
   scene:{
     desc:"{A}番がブロックに跳んだが、タッチネットして相手の得点になった。",
     ball:[{fx:150,fy:96,tx:150,ty:185}],
     actors:[{n:"A",side:"home",x:150,y:128,jump:true},{n:11,side:"away",x:150,y:96,jump:true}],
     hlHome:[],hlAway:[],result:"bad",
   },
   answer:"{A}B=",variants:["{A}B="],
   explanation:"タッチネット等でブロック失敗・失点 = B=。"},

  {skill:"E",level:1,
   players:{A:10},
   scene:{
     desc:"セッター{A}番がトスを上げた。",
     ball:[{fx:150,fy:162,tx:150,ty:130},{fx:150,fy:130,tx:70,ty:130}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],
   },
   answer:"{A}E",variants:["{A}E"],
   explanation:"E = sEt（トス）。評価なしは通常のトス。"},

  {skill:"D",level:1,
   players:{A:8},
   scene:{
     desc:"相手スパイクを自チーム{A}番がディグした。",
     ball:[{fx:230,fy:98,tx:150,ty:162},{fx:150,fy:162,tx:150,ty:145}],
     actors:[{n:"A",side:"home",x:150,y:160},{n:4,side:"away",x:230,y:98,jump:true}],
     hlHome:[8],hlAway:[],
   },
   answer:"{A}D",variants:["{A}D","{A}D!"],
   explanation:"D = Dig（スパイクレシーブ）。評価なし（または!）は普通のディグ。"},

  {skill:"D",level:1,
   players:{A:6},
   scene:{
     desc:"相手のスパイクを{A}番がディグできなかった。",
     ball:[{fx:230,fy:98,tx:180,ty:175},{fx:180,fy:175,tx:120,ty:222}],
     actors:[{n:"A",side:"home",x:180,y:175},{n:9,side:"away",x:230,y:96,jump:true}],
     hlHome:[],hlAway:[],result:"bad",
   },
   answer:"{A}D=",variants:["{A}D="],
   explanation:"ディグミス（拾えず失点）= D=。"},

  {skill:"R",level:1,
   players:{A:3},
   scene:{
     desc:"{A}番がレセプションした。",
     ball:[{fx:150,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],
   },
   answer:"{A}R",variants:["{A}R","{A}R!"],
   explanation:"R = Reception（レセプション）。評価なし（または!）は普通のレセプション。"},

  {skill:"R",level:1,
   players:{A:5},
   scene:{
     desc:"{A}番がレセプションをミスした。",
     ball:[{fx:150,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:25,ty:225}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"miss",
   },
   answer:"{A}R=",variants:["{A}R="],
   explanation:"レセプションミス = {A}R=。相手サーブエースと同義。"},

  {skill:"E",level:1,
   players:{A:10},
   scene:{
     desc:"{A}番がセットしたが、ボールがネットを越えアウトになった。",
     ball:[{fx:150,fy:162,tx:150,ty:130},{fx:150,fy:130,tx:150,ty:60}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],result:"miss",
   },
   answer:"{A}E=",variants:["{A}E="],
   explanation:"セットミス（ネット越えアウト）= E=。"},

  {skill:"A",level:1,
   players:{A:5},
   scene:{
     desc:"{A}番がスパイクを打ったが相手にブロックをされた。",
     ball:[{fx:70,fy:128,tx:150,ty:115,spike:true},{fx:150,fy:115,tx:288,ty:85}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:7,side:"away",x:150,y:96,jump:true}],
     hlHome:[4],hlAway:[],result:"bad",
   },
   answer:"{A}A/",variants:["{A}A/"],
   explanation:"スパイクがブロックされた = A/。ブロックアウト（相手コートに戻る）は「/」。"},

  // ── LV2: 評価 + 味方/相手ランダム（12問, sideRandom）──────────
  {skill:"R",level:2,sideRandom:true,
   players:{A:3},
   scene:{
     desc:"{PRE}{A}番のレセプションが完璧だった（評価#）。",
     ball:[{fx:150,fy:15,tx:70,ty:193},{fx:70,fy:193,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}R#",variants:["{APRE}{A}R#"],
   explanation:"{APRE}{A}R# = {PRE}{A}番のパーフェクトレセプション。セッターが自由にトスを上げられる。"},

  {skill:"R",level:2,sideRandom:true,
   players:{A:4},
   scene:{
     desc:"{PRE}{A}番のレセプション評価は+（優れた）。",
     ball:[{fx:150,fy:15,tx:70,ty:193},{fx:70,fy:193,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}R+",variants:["{APRE}{A}R+"],
   explanation:"{APRE}{A}R+ = {PRE}{A}番の優れたレセプション。"},

  {skill:"R",level:2,sideRandom:true,
   players:{A:7},
   scene:{
     desc:"{PRE}{A}番のレセプション評価は！（普通）。",
     ball:[{fx:150,fy:15,tx:150,ty:193},{fx:150,fy:193,tx:150,ty:162}],
     actors:[{n:"A",side:"home",x:150,y:193}],
     hlHome:[6],hlAway:[],
   },
   answer:"{APRE}{A}R!",variants:["{APRE}{A}R!","{APRE}{A}R"],
   explanation:"{APRE}{A}R! = {PRE}{A}番の普通のレセプション。評価なしと同義。"},

  {skill:"R",level:2,sideRandom:true,
   players:{A:9},
   scene:{
     desc:"{PRE}{A}番のレセプション評価はー（やや悪い）。",
     ball:[{fx:150,fy:15,tx:230,ty:193},{fx:230,fy:193,tx:150,ty:195}],
     actors:[{n:"A",side:"home",x:230,y:193}],
     hlHome:[1],hlAway:[],result:"bad",
   },
   answer:"{APRE}{A}R-",variants:["{APRE}{A}R-"],
   explanation:"{APRE}{A}R- = {PRE}{A}番のやや悪いレセプション。セッターの選択肢が狭まる。"},

  {skill:"D",level:2,sideRandom:true,
   players:{A:8},
   scene:{
     desc:"{PRE}{A}番のディグ評価は+（優れた）。",
     ball:[{fx:230,fy:96,tx:150,ty:162}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],result:"good",
   },
   answer:"{APRE}{A}D+",variants:["{APRE}{A}D+"],
   explanation:"{APRE}{A}D+ = {PRE}{A}番の優れたディグ。セッターが上げやすい好レシーブ。"},

  {skill:"D",level:2,sideRandom:true,
   players:{A:11},
   scene:{
     desc:"{PRE}{A}番のディグ評価は！（普通）。",
     ball:[{fx:230,fy:96,tx:150,ty:162}],
     actors:[{n:"A",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],
   },
   answer:"{APRE}{A}D!",variants:["{APRE}{A}D!","{APRE}{A}D"],
   explanation:"{APRE}{A}D! = {PRE}{A}番の普通のディグ。評価なしと同義。"},

  {skill:"D",level:2,sideRandom:true,
   players:{A:6},
   scene:{
     desc:"{PRE}{A}番のディグ評価はー（やや悪い）。",
     ball:[{fx:230,fy:96,tx:230,ty:193}],
     actors:[{n:"A",side:"home",x:230,y:193}],
     hlHome:[1],hlAway:[],result:"bad",
   },
   answer:"{APRE}{A}D-",variants:["{APRE}{A}D-"],
   explanation:"{APRE}{A}D- = {PRE}{A}番のやや悪いディグ。セッターの選択肢が狭まる。"},

  {skill:"S",level:2,sideRandom:true,
   players:{A:7},
   scene:{
     desc:"{PRE}{A}番のサーブがエースになった！",
     ball:[{fx:150,fy:218,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:150,y:218}],
     hlHome:[6],hlAway:[8],result:"ace",
   },
   answer:"{APRE}{A}S#",variants:["{APRE}{A}S#"],
   explanation:"{APRE}{A}S# = {PRE}{A}番のサーブエース。"},

  {skill:"S",level:2,sideRandom:true,
   players:{A:9},
   scene:{
     desc:"{PRE}{A}番のサーブがアウトになった。",
     ball:[{fx:150,fy:218,tx:150,ty:8}],
     actors:[{n:"A",side:"home",x:150,y:218}],
     hlHome:[6],hlAway:[],result:"miss",
   },
   answer:"{APRE}{A}S=",variants:["{APRE}{A}S="],
   explanation:"{APRE}{A}S= = {PRE}{A}番のサーブミス（ネット/アウト）。"},

  {skill:"A",level:2,sideRandom:true,
   players:{A:5},
   scene:{
     desc:"{PRE}{A}番がスパイクを打って得点！",
     ball:[{fx:70,fy:128,tx:110,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"ace",
   },
   answer:"{APRE}{A}A#",variants:["{APRE}{A}A#"],
   explanation:"{APRE}{A}A# = {PRE}{A}番のスパイク決定。"},

  {skill:"A",level:2,sideRandom:true,
   players:{A:11},
   scene:{
     desc:"{PRE}{A}番のスパイクがアウトになった。",
     ball:[{fx:70,fy:128,tx:30,ty:215,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[],result:"miss",
   },
   answer:"{APRE}{A}A=",variants:["{APRE}{A}A="],
   explanation:"{APRE}{A}A= = {PRE}{A}番のスパイクミス（アウト/ネット）。"},

  {skill:"B",level:2,sideRandom:true,
   players:{A:2},
   scene:{
     desc:"{PRE}{A}番がブロックして得点！",
     ball:[{fx:150,fy:96,tx:150,ty:185}],
     actors:[{n:"A",side:"home",x:150,y:128,jump:true}],
     hlHome:[3],hlAway:[],result:"ace",
   },
   answer:"{APRE}{A}B#",variants:["{APRE}{A}B#"],
   explanation:"{APRE}{A}B# = {PRE}{A}番のブロック決定。"},

  // ── LV3: コンパウンドコード（16問）────────────────────────────
  {skill:"S",level:3,
   compound:true,
   players:{A:7,B:3},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がレシーブした（評価！）。コンパウンドコードで入力せよ。",
     ball:[{fx:55,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:150,ty:162}],
     actors:[{n:"A",side:"away",x:55,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[1],
   },
   answer:"a{A}S.{B}!",variants:["a{A}S.{B}!","a{A}S.{B}"],
   explanation:"a{A}S.{B}! → CODE1: a{A}SH（相手{A}番サーブ）/ CODE2: *{B}RH!（自チーム{B}番の普通レセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:8,B:3},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番が優れたレセプション（評価+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:150,ty:130}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"good",
   },
   answer:"a{A}S.{B}+",variants:["a{A}S.{B}+"],
   explanation:"a{A}S.{B}+ → CODE1: a{A}SH / CODE2: *{B}RH+（自チーム{B}番の優れたレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:6,B:4},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がレシーブミスした。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:195}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"miss",
   },
   answer:"a{A}S.{B}=",variants:["a{A}S.{B}="],
   explanation:"a{A}S.{B}= → CODE1: a{A}SH / CODE2: *{B}RH=（自チーム{B}番のレセプションミス）。相手サーブエースと同義。"},

{skill:"S",level:3, compound:true,
   players:{A:12,B:7},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がレシーブをそのまま相手コートに返してしまった（オーバーパス）。コンパウンドで入力せよ。",
     ball:[{fx:150,fy:15,tx:150,ty:195},{fx:150,fy:195,tx:150,ty:34}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:150,y:193}],
     hlHome:[6],hlAway:[6], result:"miss"
   },
   answer:"a{A}S.{B}/", variants:["a{A}S.{B}/"],
   explanation:"a{A}S.{B}/ → CODE1: a{A}SH / CODE2: *{B}RH/（自チーム{B}番のオーバーパス）。R/ = レセプションがそのまま相手コートへ返ってしまった。"},



  {skill:"S",level:3,
   compound:true,
   players:{A:7,B:3},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番がレセプションミスした。コンパウンドコードで入力せよ。",
     ball:[{fx:55,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:55,y:220},{n:"B",side:"away",x:150,y:34}],
     hlHome:[5],hlAway:[6],result:"ace",
   },
   answer:"{A}S.{B}=",variants:["{A}S.{B}="],
   explanation:"{A}S.{B}= → CODE1: *{A}SH / CODE2: a{B}RH=（相手{B}番のレセプションミス）。サーブエースと同義。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:5,B:8},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番がブロック決定した。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:128,tx:150,ty:66,spike:true},{fx:150,fy:66,tx:110,ty:185}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:"B",side:"away",x:150,y:66,jump:true}],
     hlHome:[4],hlAway:[8],result:"ace",
   },
   answer:"{A}A.{B}#",variants:["{A}A.{B}#"],
   explanation:"{A}A.{B}# → CODE1: *{A}AH/（ブロックされた）/ CODE2: a{B}BH#（相手{B}番ブロック決定）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:2,B:9},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番がディグでつないだ。コンパウンドコードで入力せよ。",
     ball:[{fx:230,fy:128,tx:150,ty:66,spike:true},{fx:150,fy:66,tx:150,ty:130}],
     actors:[{n:"A",side:"home",x:230,y:126,jump:true},{n:"B",side:"away",x:70,y:66}],
     hlHome:[2],hlAway:[8],
   },
   answer:"{A}A.{B}D",variants:["{A}A.{B}D","{A}A.{B}D!"],
   explanation:"{A}A.{B}D → CODE1: *{A}AH / CODE2: a{B}DH（相手{B}番のディグ）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:7,B:3},
   scene:{
     desc:"{A}番がAクイック（PA）ゾーン1方向に打ったが、相手{B}番にブロックされた。",
     ball:[{fx:150,fy:130,tx:70,ty:98,spike:true},{fx:70,fy:98,tx:100,ty:185}],
     actors:[{n:"A",side:"home",x:150,y:130,jump:true},{n:"B",side:"away",x:70,y:96,jump:true}],
     hlHome:[3],hlAway:[1],result:"ace",
   },
   answer:"{A}PA1.{B}#",variants:["{A}PA1.{B}#"],
   explanation:"{A}PA1.{B}# → CODE1: *{A}PA1/（Aクイックがブロックされた）/ CODE2: a{B}BH#（相手{B}番ブロック決定）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:4,B:9},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番がパーフェクトレセプション（#）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:55,fy:222,tx:150,ty:34},{fx:150,fy:34,tx:150,ty:98}],
     actors:[{n:"A",side:"home",x:55,y:220},{n:"B",side:"away",x:150,y:34}],
     hlHome:[5],hlAway:[8],result:"good",
   },
   answer:"{A}S.{B}#",variants:["{A}S.{B}#"],
   explanation:"{A}S.{B}# → CODE1: *{A}SH / CODE2: a{B}RH#（相手{B}番のパーフェクトレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:11,B:7},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番が優れたレセプション（+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:150,ty:34},{fx:150,fy:34,tx:150,ty:98}],
     actors:[{n:"A",side:"home",x:245,y:220},{n:"B",side:"away",x:150,y:34}],
     hlHome:[1],hlAway:[8],result:"good",
   },
   answer:"{A}S.{B}+",variants:["{A}S.{B}+"],
   explanation:"{A}S.{B}+ → CODE1: *{A}SH / CODE2: a{B}RH+（相手{B}番の優れたレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:6,B:2},
   scene:{
     desc:"{A}番がサーブを打ち、相手{B}番のレセプションがやや悪かった（評価ー）。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:222,tx:230,ty:34}],
     actors:[{n:"A",side:"home",x:150,y:220},{n:"B",side:"away",x:230,y:34}],
     hlHome:[6],hlAway:[5],result:"good",
   },
   answer:"{A}S.{B}-",variants:["{A}S.{B}-"],
   explanation:"{A}S.{B}- → CODE1: *{A}SH / CODE2: a{B}RH-（相手{B}番のやや悪いレセプション）。"},

  {skill:"S",level:3,
   compound:true,
   players:{A:9,B:5},
   scene:{
     desc:"相手{A}番がサーブを打ち、自チーム{B}番がパーフェクトレセプション（#）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:15,tx:70,ty:195},{fx:70,fy:195,tx:150,ty:130}],
     actors:[{n:"A",side:"away",x:150,y:18},{n:"B",side:"home",x:70,y:193}],
     hlHome:[5],hlAway:[6],result:"good",
   },
   answer:"a{A}S.{B}#",variants:["a{A}S.{B}#"],
   explanation:"a{A}S.{B}# → CODE1: a{A}SH（相手{A}番サーブ）/ CODE2: *{B}RH#（自チーム{B}番のパーフェクトレセプション）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:9,B:2},
   scene:{
     desc:"相手{A}番がスパイクを打ち、自チーム{B}番がブロック決定した。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:66,tx:70,ty:115},{fx:70,fy:115,tx:90,ty:185}],
     actors:[{n:"A",side:"away",x:70,y:64,jump:true},{n:"B",side:"home",x:70,y:128,jump:true}],
     hlHome:[4],hlAway:[9],result:"ace",
   },
   answer:"a{A}A.{B}#",variants:["a{A}A.{B}#"],
   explanation:"a{A}A.{B}# → CODE1: a{A}AH/（相手{A}番のスパイクがブロックされた）/ CODE2: *{B}BH#（自チーム{B}番のブロック決定）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:11,B:8},
   scene:{
     desc:"相手{A}番がスパイクを打ち、自チーム{B}番がディグでつないだ。コンパウンドコードで入力せよ。",
     ball:[{fx:230,fy:66,tx:150,ty:162}],
     actors:[{n:"A",side:"away",x:230,y:64,jump:true},{n:"B",side:"home",x:150,y:162}],
     hlHome:[8],hlAway:[],result:"good",
   },
   answer:"a{A}A.{B}D",variants:["a{A}A.{B}D","a{A}A.{B}D!"],
   explanation:"a{A}A.{B}D → CODE1: a{A}AH / CODE2: *{B}DH（自チーム{B}番のディグ）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:3,B:6},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番が優れたディグでつないだ。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:128,tx:150,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:"B",side:"away",x:150,y:66}],
     hlHome:[4],hlAway:[8],result:"good",
   },
   answer:"{A}A.{B}D+",variants:["{A}A.{B}D+"],
   explanation:"{A}A.{B}D+ → CODE1: *{A}AH / CODE2: a{B}DH+（相手{B}番の優れたディグ）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:8,B:4},
   scene:{
     desc:"{A}番がスパイクを打ち、相手{B}番がブロックミスして得点。コンパウンドコードで入力せよ。",
     ball:[{fx:70,fy:128,tx:150,ty:66,spike:true},{fx:150,fy:66,tx:285,ty:25}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true},{n:"B",side:"away",x:150,y:66,jump:true}],
     hlHome:[4],hlAway:[8],result:"ace",
   },
   answer:"{A}A.{B}=",variants:["{A}A.{B}="],
   explanation:"{A}A.{B}= → CODE1: *{A}AH#（スパイク決定）/ CODE2: a{B}BH=（相手{B}番のブロックミス）。"},

  {skill:"A",level:3,
   compound:true,
   players:{A:11,B:8},
   scene:{
     desc:"相手{A}番がスパイク、自チーム{B}番がディグしたが、スパイク得点になった。コンパウンドコードで入力せよ。",
     ball:[{fx:230,fy:66,tx:150,ty:162},{fx:150,fy:162,tx:90,ty:222}],
     actors:[{n:"A",side:"away",x:230,y:64,jump:true},{n:"B",side:"home",x:150,y:162}],
     hlHome:[],hlAway:[],result:"bad",
   },
   answer:"a{A}A.{B}D=",variants:["a{A}A.{B}D="],
   explanation:"a{A}A.{B}D= → CODE1: a{A}AH / CODE2: *{B}DH=（自チーム{B}番のディグミス、失点）。"},

  // ── LV4: ゾーン・サーブ種別詳細（12問）─────────────────────
  {skill:"S",level:4,
   compound:true,
   players:{A:7,B:4},
   scene:{
     desc:"{A}番がゾーン1（右後）から、ゾーン5にジャンプフローターサーブを打って、相手{B}番がパーフェクトレセプション。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:55,ty:50,curve:true},{fx:55,fy:50,tx:150,ty:98}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true},{n:"B",side:"away",x:55,y:48}],
     hlHome:[1],hlAway:[5],result:"good",
   },
   answer:"{A}SM15.{B}#",variants:["{A}SM15.{B}#","{A}SM1.{B}#5"],
   explanation:"{A}SM15.{B}# → CODE1: *{A}SM15（ゾーン1→5 J.フローター）/ CODE2: a{B}RH#（相手{B}番のパーフェクトレセプション）。"},

  {skill:"S",level:4,
   players:{A:11},
   scene:{
     desc:"{A}番がゾーン6（中後）から相手ゾーン5にジャンピングサーブを打ったがネット。",
     ball:[{fx:150,fy:222,tx:150,ty:112,net:true}],
     actors:[{n:"A",side:"home",x:150,y:220,jump:true}],
     hlHome:[6],hlAway:[],result:"miss",
   },
   answer:"{A}SQ65=",variants:["{A}SQ65="],
   explanation:"SQ65 = ゾーン6からゾーン5へのジャンピングサーブ。ネットミス = {A}SQ65=。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:1,B:5},
   scene:{
     desc:"{A}番がゾーン1（右後）から相手ゾーン1にジャンピングサーブを打ち、相手{B}番がはじいてエース！",
     ball:[{fx:245,fy:222,tx:245,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true},{n:"B",side:"away",x:245,y:34}],
     hlHome:[1],hlAway:[5],result:"ace",
   },
   answer:"{A}S11.{B}=",variants:["{A}S11.{B}="],
   explanation:"{A}S11.{B}= → CODE1: *{A}SH11（ゾーン1→1サーブ）/ CODE2: a{B}RH=（相手{B}番のレセプションミス）。"},

  {skill:"S",level:4,
   players:{A:9},
   scene:{
     desc:"{A}番がゾーン6（中後）からゾーン8（中央）にジャンプフローターサーブを打った。",
     ball:[{fx:150,fy:222,tx:150,ty:66,curve:true}],
     actors:[{n:"A",side:"home",x:150,y:220,jump:true}],
     hlHome:[6],hlAway:[8],
   },
   answer:"{A}SM68",variants:["{A}SM68"],
   explanation:"SM68 = ゾーン6からゾーン8へのジャンプフローター。{A}SM68。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:3,B:6},
   scene:{
     desc:"{A}番がゾーン1からゾーン6にジャンプフローターサーブを打ち、相手{B}番が優れたレセプション（評価+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:150,ty:66,curve:true},{fx:150,fy:66,tx:150,ty:98}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true},{n:"B",side:"away",x:150,y:64}],
     hlHome:[1],hlAway:[8],result:"good",
   },
   answer:"{A}SM16.{B}+",variants:["{A}SM16.{B}+"],
   explanation:"{A}SM16.{B}+ → CODE1: *{A}SM16（ゾーン1→6 J.フローター）/ CODE2: a{B}RH+（相手{B}番の優れたレセプション）。"},

  {skill:"A",level:4,
   players:{A:5},
   scene:{
     desc:"{A}番がレフト平行（PV）をゾーン7に打って決まった！",
     ball:[{fx:70,fy:128,tx:230,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[7],result:"ace",
   },
   answer:"{A}PV7#",variants:["{A}PV7#"],
   explanation:"PV = レフト平行。ゾーン7 = AWAY右エリア。{A}PV7#。"},

  {skill:"S",level:4,
   players:{A:6},
   scene:{
     desc:"{A}番がゾーン1（右後）からゾーン6（中央）にジャンピングサーブを打ちエースになった！",
     ball:[{fx:245,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true}],
     hlHome:[1],hlAway:[8],result:"ace",
   },
   answer:"{A}SQ16#",variants:["{A}SQ16#"],
   explanation:"SQ16 = ゾーン1からゾーン6へのジャンピングサーブ。エース = {A}SQ16#。"},

  {skill:"S",level:4,
   players:{A:14},
   scene:{
     desc:"{A}番がゾーン5（左後）からゾーン8（中央）にジャンプフローターサーブを打った。",
     ball:[{fx:55,fy:222,tx:150,ty:66,curve:true}],
     actors:[{n:"A",side:"home",x:55,y:220,jump:true}],
     hlHome:[5],hlAway:[8],
   },
   answer:"{A}SM58",variants:["{A}SM58"],
   explanation:"SM58 = ゾーン5からゾーン8へのジャンプフローター。{A}SM58。"},

  {skill:"A",level:4,
   players:{A:3},
   scene:{
     desc:"{A}番がライト平行（PZ）をゾーン7に打って決まった！",
     ball:[{fx:230,fy:128,tx:230,ty:66,spike:true}],
     actors:[{n:"A",side:"home",x:230,y:126,jump:true}],
     hlHome:[2],hlAway:[7],result:"ace",
   },
   answer:"{A}PZ7#",variants:["{A}PZ7#"],
   explanation:"PZ = ライト平行（ゾーン2から打つ）。ゾーン7 = AWAY右エリア。{A}PZ7#。"},

  {skill:"A",level:4,
   players:{A:8},
   scene:{
     desc:"{A}番がレフト平行（PV）をゾーン1に打って決まった！",
     ball:[{fx:70,fy:128,tx:70,ty:34,spike:true}],
     actors:[{n:"A",side:"home",x:70,y:126,jump:true}],
     hlHome:[4],hlAway:[1],result:"ace",
   },
   answer:"{A}PV1#",variants:["{A}PV1#"],
   explanation:"PV = レフト平行。ゾーン1 = AWAYの右後。{A}PV1#。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:2,B:7},
   scene:{
     desc:"{A}番がゾーン1から相手ゾーン6にジャンピングサーブを打ち、相手{B}番がレセプションミスした。コンパウンドコードで入力せよ。",
     ball:[{fx:245,fy:222,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:245,y:220,jump:true},{n:"B",side:"away",x:150,y:34}],
     hlHome:[1],hlAway:[8],result:"ace",
   },
   answer:"{A}SQ16.{B}=",variants:["{A}SQ16.{B}="],
   explanation:"{A}SQ16.{B}= → CODE1: *{A}SQ16（ゾーン1→6 ジャンピングサーブ）/ CODE2: a{B}RH=（相手{B}番のレセプションミス）。"},

  {skill:"S",level:4,
   compound:true,
   players:{A:5,B:3},
   scene:{
     desc:"{A}番がゾーン6から相手ゾーン5にジャンプフローターを打ち、相手{B}番が優れたレセプション（評価+）で返した。コンパウンドコードで入力せよ。",
     ball:[{fx:150,fy:222,tx:55,ty:66,curve:true},{fx:55,fy:66,tx:150,ty:98}],
     actors:[{n:"A",side:"home",x:150,y:220,jump:true},{n:"B",side:"away",x:55,y:64}],
     hlHome:[6],hlAway:[5],result:"good",
   },
   answer:"{A}SM65.{B}+",variants:["{A}SM65.{B}+"],
   explanation:"{A}SM65.{B}+ → CODE1: *{A}SM65（ゾーン6→5 ジャンプフローター）/ CODE2: a{B}RH+（相手{B}番の優れたレセプション）。"},

  // ── LV5: マルチコード（8問）────────────────────────────────
  {skill:"S",level:5,
   multiCode:true,
   players:{A:1,B:3,C:4,D:6},
   scene:{
     desc:"{A}番がゾーン1から相手ゾーン6にジャンピングサーブ。相手{B}番がパーフェクトレセプション。続いて相手{C}番がゾーン7にレフト平行を打ち、味方{D}番がブロックミス。2コードをスペースで区切って入力せよ。",
     ball:[{fx:245,fy:220,tx:150,ty:60},{fx:150,fy:60,tx:150,ty:85}],
     actors:[{n:"A",side:"home",x:245,y:218,jump:true},{n:"B",side:"away",x:150,y:58},{n:"C",side:"away",x:70,y:94,jump:true},{n:"D",side:"home",x:200,y:130,jump:true}],
     hlHome:[3],hlAway:[6,8],result:"bad",
   },
   answer:"{A}SQ16.{B}# a{C}PV7.{D}=",variants:["{A}SQ16.{B}# a{C}PV7.{D}="],
   explanation:"複合1: {A}SQ16.{B}# → *{A}SQ16 / a{B}RH#（ゾーン1→6ジャンピングサーブ→相手{B}番パーフェクトレセプション）　複合2: a{C}PV7.{D}= → a{C}PV7# / *{D}BH=（相手{C}番ゾーン7レフト平行→味方{D}番ブロックミス）。"},

  {skill:"S",level:5,
   multiCode:true,
   players:{A:5,B:2,C:7,D:9},
   scene:{
     desc:"{A}番がゾーン5から相手ゾーン1にジャンプフローターサーブ。相手{B}番のレセプション評価はー。続いて相手{C}番がゾーン4にライト平行を打ち、味方{D}番がブロックアウト。2コードをスペースで区切って入力せよ。",
     ball:[{fx:55,fy:220,tx:245,ty:60,curve:true},{fx:245,fy:60,tx:150,ty:34}],
     actors:[{n:"A",side:"home",x:55,y:218,jump:true},{n:"B",side:"away",x:245,y:58},{n:"C",side:"away",x:230,y:94,jump:true},{n:"D",side:"home",x:70,y:130,jump:true}],
     hlHome:[1,5],hlAway:[5,7],result:"bad",
   },
   answer:"{A}SM51.{B}- a{C}PZ4.{D}/",variants:["{A}SM51.{B}- a{C}PZ4.{D}/"],
   explanation:"複合1: {A}SM51.{B}- → *{A}SM51 / a{B}RH-（ゾーン5→1ジャンプフローター→相手{B}番レセプションー）　複合2: a{C}PZ4.{D}/ → a{C}PZ4 / *{D}BH/（相手{C}番ゾーン4ライト平行→味方{D}番ブロックアウト）。"},

  {skill:"S",level:5,
   multiCode:true,
   players:{A:2,B:8,C:6,D:4},
   scene:{
     desc:"{A}番がゾーン6から相手ゾーン5にジャンプフローターサーブ。相手{B}番のレセプション評価は！。続いて相手{C}番がゾーン8にAクイックを打ち、味方{D}番がブロック決定。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:220,tx:55,ty:60,curve:true},{fx:55,fy:60,tx:150,ty:85}],
     actors:[{n:"A",side:"home",x:150,y:218,jump:true},{n:"B",side:"away",x:55,y:58},{n:"C",side:"away",x:150,y:94,jump:true},{n:"D",side:"home",x:150,y:130,jump:true}],
     hlHome:[2,5],hlAway:[6,8],result:"ace",
   },
   answer:"{A}SM65.{B}! a{C}PA8.{D}#",variants:["{A}SM65.{B}! a{C}PA8.{D}#"],
   explanation:"複合1: {A}SM65.{B}! → *{A}SM65 / a{B}RH!（ゾーン6→5ジャンプフローター→相手{B}番レセプション！）　複合2: a{C}PA8.{D}# → a{C}PA8/ / *{D}BH#（相手{C}番ゾーン8Aクイック→味方{D}番ブロック決定）。"},

  {skill:"R",level:5,
   multiCode:true,
   players:{A:9,B:2,C:5,D:8},
   scene:{
     desc:"相手{A}番がゾーン5から自ゾーン6にジャンピングサーブ。自チーム{B}番がパーフェクトレセプション。続いて{C}番がゾーン7にレフト平行を打ち、相手{D}番がブロック決定。2コードをスペースで区切って入力せよ。",
     ball:[{fx:55,fy:15,tx:150,ty:195},{fx:150,fy:195,tx:150,ty:130}],
     actors:[{n:"A",side:"away",x:55,y:18,jump:true},{n:"B",side:"home",x:150,y:193},{n:"C",side:"home",x:70,y:126,jump:true},{n:"D",side:"away",x:150,y:66,jump:true}],
     hlHome:[5,4],hlAway:[7],result:"bad",
   },
   answer:"a{A}SQ56.{B}# {C}PV7.{D}#",variants:["a{A}SQ56.{B}# {C}PV7.{D}#"],
   explanation:"複合1: a{A}SQ56.{B}# → a{A}SQ56 / *{B}RH#（相手{A}番ゾーン5→6ジャンピングサーブ→自チーム{B}番パーフェクトレセプション）　複合2: {C}PV7.{D}# → *{C}PV7/ / a{D}BH#（{C}番ゾーン7レフト平行→相手{D}番ブロック決定）。"},

  {skill:"R",level:5,
   multiCode:true,
   players:{A:7,B:4,C:11,D:3},
   scene:{
     desc:"相手{A}番がゾーン1から自ゾーン5にジャンプフローターサーブ。自チーム{B}番のレセプション評価は+。続いて{C}番がゾーン5にAクイックを打ち、相手{D}番が優れたディグで返した。2コードをスペースで区切って入力せよ。",
     ball:[{fx:245,fy:15,tx:55,ty:195},{fx:55,fy:195,tx:150,ty:130}],
     actors:[{n:"A",side:"away",x:245,y:18,jump:true},{n:"B",side:"home",x:55,y:193},{n:"C",side:"home",x:150,y:126,jump:true},{n:"D",side:"away",x:55,y:66}],
     hlHome:[5,3],hlAway:[],result:"good",
   },
   answer:"a{A}SM15.{B}+ {C}PA5.{D}D+",variants:["a{A}SM15.{B}+ {C}PA5.{D}D+"],
   explanation:"複合1: a{A}SM15.{B}+ → a{A}SM15 / *{B}RH+（相手{A}番ゾーン1→5ジャンプフローター→自チーム{B}番レセプション+）　複合2: {C}PA5.{D}D+ → *{C}PA5 / a{D}DH+（{C}番ゾーン5Aクイック→相手{D}番優れたディグ）。"},

  {skill:"A",level:5,
   multiCode:true,
   players:{A:3,B:6,C:9,D:2},
   scene:{
     desc:"{A}番がゾーン6から相手ゾーン1にジャンピングサーブ。相手{B}番がパーフェクトレセプション。続いて相手{C}番がゾーン7にライト平行を打ち、味方{D}番がブロックミス。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:220,tx:245,ty:60},{fx:245,fy:60,tx:150,ty:85}],
     actors:[{n:"A",side:"home",x:150,y:218,jump:true},{n:"B",side:"away",x:245,y:58},{n:"C",side:"away",x:230,y:94,jump:true},{n:"D",side:"home",x:70,y:130,jump:true}],
     hlHome:[],hlAway:[8,2],result:"bad",
   },
   answer:"{A}SQ61.{B}# a{C}PZ7.{D}=",variants:["{A}SQ61.{B}# a{C}PZ7.{D}="],
   explanation:"複合1: {A}SQ61.{B}# → *{A}SQ61 / a{B}RH#（ゾーン6→1ジャンピングサーブ→相手{B}番パーフェクトレセプション）　複合2: a{C}PZ7.{D}= → a{C}PZ7# / *{D}BH=（相手{C}番ゾーン7ライト平行→味方{D}番ブロックミス）。"},

  {skill:"D",level:5,
   multiCode:true,
   players:{A:8,B:3,C:5,D:11},
   scene:{
     desc:"相手{A}番がゾーン6から自ゾーン8にジャンプフローターサーブ。自チーム{B}番のレセプション評価はー。続いて{C}番がゾーン4にレフト平行を打ち、相手{D}番がディグでつないだ。2コードをスペースで区切って入力せよ。",
     ball:[{fx:150,fy:15,tx:150,ty:195},{fx:150,fy:195,tx:150,ty:162}],
     actors:[{n:"A",side:"away",x:150,y:18,jump:true},{n:"B",side:"home",x:150,y:193},{n:"C",side:"home",x:70,y:126,jump:true},{n:"D",side:"away",x:70,y:66}],
     hlHome:[1,4],hlAway:[],result:"good",
   },
   answer:"a{A}SM68.{B}- {C}PV4.{D}D",variants:["a{A}SM68.{B}- {C}PV4.{D}D"],
   explanation:"複合1: a{A}SM68.{B}- → a{A}SM68 / *{B}RH-（相手{A}番ゾーン6→8ジャンプフローター→自チーム{B}番レセプションー）　複合2: {C}PV4.{D}D → *{C}PV4 / a{D}DH（{C}番ゾーン4レフト平行→相手{D}番ディグ）。"},

  {skill:"B",level:5,
   multiCode:true,
   players:{A:7,B:2,C:6,D:1},
   scene:{
     desc:"相手{A}番がゾーン5から自ゾーン6にジャンプフローターサーブ。自チーム{B}番のレセプション評価は+。続いて{C}番がゾーン1にAクイックを打ち、相手{D}番がブロック決定。2コードをスペースで区切って入力せよ。",
     ball:[{fx:55,fy:15,tx:150,ty:195},{fx:150,fy:195,tx:150,ty:130}],
     actors:[{n:"A",side:"away",x:55,y:18,jump:true},{n:"B",side:"home",x:150,y:193},{n:"C",side:"home",x:150,y:128,jump:true},{n:"D",side:"away",x:245,y:66,jump:true}],
     hlHome:[4],hlAway:[8,3],result:"bad",
   },
   answer:"a{A}SM56.{B}+ {C}PA1.{D}#",variants:["a{A}SM56.{B}+ {C}PA1.{D}#"],
   explanation:"複合1: a{A}SM56.{B}+ → a{A}SM56 / *{B}RH+（相手{A}番ゾーン5→6ジャンプフローター→自チーム{B}番レセプション+）　複合2: {C}PA1.{D}# → *{C}PA1/ / a{D}BH#（{C}番ゾーン1Aクイック→相手{D}番ブロック決定）。"},
];

export default QUESTIONS_RAW;
